### ISSUE TITLE
still failing...

### ISSUE THREAD

**Issue by mjburton11** [convexengineering/turbofan#12]
@galbramc how do I get this repo to test again?

Also, can I get a Jenkins account?

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
all repos will start testing with that command. Yes you can get an account on acdl, but you need to stop by my office. Im out of town and will be back on campus on thursday. You could also talk to Savithru to get an account on acdl.mit.edu.

**Comment by galbramc** [comment]
Oh you wanted to build the push again. For that you need an account on jenkins to trigger a new build. I fired one off for you.

**Comment by mjburton11** [comment]
Ok great.  Thanks!
